config/routes.rb
Imagenes::Application.routes.draw do
  
  get "log_out" => "sessions#destroy", :as => "log_out"
	get "log_in" => "sessions#new", :as => "log_in"
	get "sign_up" => "users#new", :as => "sign_up"

	root :to => 'schools#index'
	
  resources :cards
  
  resources :users

  resources :schools
    
  resources :sessions

  resources :cardsets

end

app/models/cardset.rb
class Cardset < ActiveRecord::Base
  attr_accessible :belongs_to, :privacy, :title
end

app/controllers/cardsets_controller.rb
class CardsetsController < ApplicationController
  # GET /cardsets
  # GET /cardsets.json
  def index
    @cardsets = Cardset.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cardsets }
    end
  end

  # GET /cardsets/1
  # GET /cardsets/1.json
  def show
    @cardset = Cardset.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cardset }
    end
  end

  # GET /cardsets/new
  # GET /cardsets/new.json
  def new
    @cardset = Cardset.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cardset }
    end
  end

  # GET /cardsets/1/edit
  def edit
    @cardset = Cardset.find(params[:id])
  end

  # POST /cardsets
  # POST /cardsets.json
  def create
    @cardset = Cardset.new(params[:cardset])

    respond_to do |format|
      if @cardset.save
        format.html { redirect_to @cardset, notice: 'Cardset was successfully created.' }
        format.json { render json: @cardset, status: :created, location: @cardset }
      else
        format.html { render action: "new" }
        format.json { render json: @cardset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cardsets/1
  # PUT /cardsets/1.json
  def update
    @cardset = Cardset.find(params[:id])

    respond_to do |format|
      if @cardset.update_attributes(params[:cardset])
        format.html { redirect_to @cardset, notice: 'Cardset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cardset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cardsets/1
  # DELETE /cardsets/1.json
  def destroy
    @cardset = Cardset.find(params[:id])
    @cardset.destroy

    respond_to do |format|
      format.html { redirect_to cardsets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cardsets_helper.rb
module CardsetsHelper
end

app/views/cardsets/_form.html.erb
<%= form_for(@cardset) do |f| %>
  <% if @cardset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cardset.errors.count, "error") %> prohibited this cardset from being saved:</h2>

      <ul>
      <% @cardset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cardsets/edit.html.erb
<h1>Editing cardset</h1>

<%= render 'form' %>

<%= link_to 'Show', @cardset %> |
<%= link_to 'Back', cardsets_path %>

app/views/cardsets/index.html.erb
<h1>My Sets</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cardsets.each do |cardset| %>
  <tr>
    <td><%= cardset.title %></td>
    <td><%= link_to 'Show', cardset %></td>
    <td><%= link_to 'Edit', edit_cardset_path(cardset) %></td>
    <td><%= link_to 'Destroy', cardset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/cardsets/new.html.erb
<h1>New Set</h1>

Examples: Chapter 1, Animals, Food, etc.<br><br>

<%= render 'form' %>

app/views/cardsets/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @cardset.title %>
</h1>


<%= link_to 'Edit', edit_cardset_path(@cardset) %>