config/routes.rb
Imagenes::Application.routes.draw do
  
  get "log_out" => "sessions#destroy", :as => "log_out"
	get "log_in" => "sessions#new", :as => "log_in"
	get "sign_up" => "users#new", :as => "sign_up"

	root :to => 'schools#index'
	
  resources :cards
  
  resources :users

  resources :schools
    
  resources :sessions

  resources :cardsets

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imágenes</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= filepicker_js_include_tag %>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">Imágenes</a>
          <div class="nav-collapse collapse">
            <ul class="nav pull-right">
            	<% if current_user %>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sets <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="/cardsets/new">New Set</a></li>
                  <li><a href="/cardsets">Manage Sets</a></li>
                </ul>
                </li>
              	<li><%= link_to "My Profile", current_user.username, { :controller => "users", :action => "user", :username => current_user.username.downcase} %></li>
              	<li><%= link_to "Log out", log_out_path %></li>
              <% else %>
              	<li><%= link_to "Sign up", sign_up_path %></li>
              	<li><%= link_to "log in", log_in_path %></li>
              <% end %>
<!--
              <% if current_user && current_user.user_type = '' %>
              	<li><%= link_to "New Set", new_cardset_path %></li>
              <% end %>
-->
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="container">

<% flash.each do |name, msg| %>
  <div id="flash"><%= content_tag :div, msg, :id => "flash_#{name}" %></div>
<% end %>

<%= yield %>

      <footer>
      	<hr>
        <p>Imágenes(RoR) v.0.5</p>
      </footer>
    </div>
        <script src="../assets/js/bootstrap-dropdown.js"></script>
</body>
</html>